version: "3.4"
services:
  api:
    image: ghcr.io/naveenss1994/fabrikam-api:main
    ports:
      - "3001:3001"

  web:
    image: ghcr.io/naveenss1994/fabrikam-web:main
    depends_on:
        - api
    environment:
        CONTENT_API_URL: http://api:3001
    ports:
        - "3000:80"
        